# Generated by Django 6.0.3 on 2026-06-22 08:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPanelProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Admin's full name", max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', help_text="Admin's gender", max_length=10)),
                ('date_of_birth', models.DateField(blank=True, help_text="Admin's date of birth", null=True)),
                ('mobile_number', models.CharField(help_text="Admin's primary mobile number", max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('alternate_mobile_number', models.CharField(blank=True, help_text="Admin's alternate mobile number (optional)", max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('is_verified_by_superuser', models.BooleanField(default=False, help_text='Only a superuser admin can toggle this to activate the admin staff account')),
                ('date_of_join', models.DateTimeField(auto_now_add=True, help_text='Date and time when admin account was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('user', models.OneToOneField(help_text='Associated BaseUser account', on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Panel Profile',
                'verbose_name_plural': 'Admin Panel Profiles',
                'ordering': ['-date_of_join'],
            },
        ),
    ]
