# Generated by Django 6.0.3 on 2026-06-23 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_adminpanelprofile_alternate_mobile_number_and_more'),
        ('lawyers', '0004_alter_lawyerprofile_bar_registration_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Current verification status', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When verification request was submitted')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When admin reviewed the request', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if rejected', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes during review', null=True)),
                ('lawyer', models.OneToOneField(help_text='Lawyer requesting verification', on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to='lawyers.lawyerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_lawyer_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lawyer Verification Request',
                'verbose_name_plural': 'Lawyer Verification Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
