# Generated by Django 6.0.3 on 2026-06-24 17:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_lawyerverificationrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPanelProfileUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, help_text='Admin primary mobile number for pending updates.', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in Indian format (10 digits starting with 6-9, or +91...', regex='^(\\+91|0)?[6-9]\\d{9}$')])),
                ('alternate_mobile_number', models.CharField(blank=True, help_text='Admin alternate mobile number for pending updates.', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in Indian format (10 digits starting with 6-9, or +91...', regex='^(\\+91|0)?[6-9]\\d{9}$')])),
                ('profile_picture', models.ImageField(blank=True, help_text='Updated profile picture submitted for approval.', null=True, upload_to='admin_update_requests/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Current review status for this update request.', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes for the superuser review, especially rejection reason.', null=True)),
                ('admin_profile', models.ForeignKey(help_text='Admin profile requesting an update.', on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='adminpanel.adminpanelprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Superuser who reviewed this update request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_admin_profile_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile Update Request',
                'verbose_name_plural': 'Admin Profile Update Requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
