# Generated by Django 6.0.3 on 2026-06-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_adminpanelprofileupdaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpanelprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the admin profile was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='adminpanelprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag for an admin panel user profile'),
        ),
    ]
