# Generated by Django 6.0.3 on 2026-06-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_adminpanelprofile_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAdminPanelProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Deleted Admin Panel Profile',
                'verbose_name_plural': 'Deleted Admin Panel Profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('adminpanel.adminpanelprofile',),
        ),
    ]
