# Generated by Django 6.0.3 on 2026-06-25 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_deletedadminpanelprofile'),
        ('clients', '0005_deletedclientprofile'),
        ('lawyers', '0010_caserequest_documents_submitted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(help_text='Primary reason for filing the report', max_length=140)),
                ('description', models.TextField(help_text='Detailed explanation of the incident leading to this report')),
                ('evidence', models.FileField(blank=True, help_text='Optional evidence file supporting the report', null=True, upload_to='report_evidence/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WARNED', 'Warned'), ('BANNED', 'Banned')], default='PENDING', help_text='Admin review status for this report', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes entered by the admin during review', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the report was reviewed by an admin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_client', models.ForeignKey(blank=True, help_text='Client being reported, if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to='clients.clientprofile')),
                ('reported_lawyer', models.ForeignKey(blank=True, help_text='Lawyer being reported, if applicable', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to='lawyers.lawyerprofile')),
                ('reporter', models.ForeignKey(help_text='User who submitted this report', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_trust_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trust Report',
                'verbose_name_plural': 'Trust Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
