# Generated by Django 6.0.3 on 2026-06-26 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_otpcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteAccountToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delete Account Token',
                'verbose_name_plural': 'Delete Account Tokens',
                'ordering': ['-created_at'],
            },
        ),
    ]
