# Generated by Django 6.0.3 on 2026-06-22 08:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text="Lawyer's full name", max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', help_text="Lawyer's gender", max_length=10)),
                ('date_of_birth', models.DateField(blank=True, help_text="Lawyer's date of birth", null=True)),
                ('bar_registration_number', models.CharField(help_text='Bar council registration/license number', max_length=50, unique=True)),
                ('state_bar_council', models.CharField(help_text='Name of the state bar council where registered', max_length=100)),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Number of years of legal practice experience', validators=[django.core.validators.MinValueValidator(0)])),
                ('specialization', models.CharField(choices=[('criminal', 'Criminal Law'), ('family', 'Family Law'), ('corporate', 'Corporate Law'), ('ip', 'Intellectual Property'), ('labor', 'Labor Law'), ('tax', 'Tax Law'), ('real_estate', 'Real Estate'), ('bankruptcy', 'Bankruptcy Law'), ('other', 'Other')], default='other', help_text='Primary area of legal specialization', max_length=50)),
                ('rating', models.FloatField(default=0.0, help_text='Professional rating (0.0 to 5.0 scale)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('verified', models.BooleanField(default=False, help_text="Is the lawyer's credentials verified by admin?")),
                ('mobile_number', models.CharField(help_text="Lawyer's primary mobile number", max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('alternate_mobile_number', models.CharField(blank=True, help_text="Lawyer's alternate mobile number (optional)", max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='Date and time when lawyer joined the platform')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('user', models.OneToOneField(help_text='Associated BaseUser account', on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lawyer Profile',
                'verbose_name_plural': 'Lawyer Profiles',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['verified', '-rating'], name='lawyers_law_verifie_f168fd_idx'), models.Index(fields=['specialization'], name='lawyers_law_special_196731_idx')],
            },
        ),
    ]
