# Generated by Django 6.0.3 on 2026-06-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='Has lawyer completed their profile and submitted for verification?'),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="Lawyer's profile picture", null=True, upload_to='lawyer_pictures/'),
        ),
    ]
