# Generated by Django 6.0.3 on 2026-06-23 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0002_lawyerprofile_is_profile_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, help_text="Lawyer's alternate mobile number (optional)", max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in Indian format (10 digits starting with 6-9, or +91...', regex='^(\\+91|0)?[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='bar_registration_number',
            field=models.CharField(blank=True, help_text='Bar council registration/license number - Must be entered by user', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='mobile_number',
            field=models.CharField(blank=True, help_text="Lawyer's primary mobile number (10 digits)", max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in Indian format (10 digits starting with 6-9, or +91...', regex='^(\\+91|0)?[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='lawyerprofile',
            name='state_bar_council',
            field=models.CharField(blank=True, help_text='Name of the state bar council where registered', max_length=100),
        ),
    ]
