# Generated by Django 6.0.3 on 2026-06-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0003_alter_lawyerprofile_alternate_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerprofile',
            name='bar_registration_number',
            field=models.CharField(help_text='Bar council registration/license number - Must be entered by user', max_length=50, unique=True),
        ),
    ]
