# Generated by Django 6.0.3 on 2026-06-24 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0004_alter_lawyerprofile_bar_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Professional biography and background', max_length=500),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hourly consultation fee in rupees', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='office_city',
            field=models.CharField(blank=True, help_text="City where the lawyer's office is located", max_length=100),
        ),
    ]
