# Generated by Django 6.0.3 on 2026-06-24 08:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0005_lawyerprofile_bio_lawyerprofile_consultation_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerProfileUpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('years_of_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, choices=[('criminal', 'Criminal Law'), ('family', 'Family Law'), ('corporate', 'Corporate Law'), ('ip', 'Intellectual Property'), ('labor', 'Labor Law'), ('tax', 'Tax Law'), ('real_estate', 'Real Estate'), ('bankruptcy', 'Bankruptcy Law'), ('other', 'Other')], max_length=50, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('consultation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('office_city', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in Indian format (10 digits starting with 6-9, or +91...', regex='^(\\+91|0)?[6-9]\\d{9}$')])),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in Indian format (10 digits starting with 6-9, or +91...', regex='^(\\+91|0)?[6-9]\\d{9}$')])),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='lawyer_updates/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Reason for rejection, if applicable.', null=True)),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='lawyers.lawyerprofile')),
            ],
        ),
    ]
