# Generated by Django 6.0.3 on 2026-06-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0006_lawyerprofileupdaterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the lawyer profile was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag for a lawyer profile'),
        ),
    ]
