# Generated by Django 6.0.3 on 2026-06-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0007_lawyerprofile_deleted_at_lawyerprofile_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedLawyerProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Deleted Lawyer Profile',
                'verbose_name_plural': 'Deleted Lawyer Profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lawyers.lawyerprofile',),
        ),
    ]
