# Generated by Django 6.0.3 on 2026-06-25 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_deletedclientprofile'),
        ('lawyers', '0008_deletedlawyerprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Client message or summary of the request')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response_message', models.TextField(blank=True, help_text='Optional lawyer response message', null=True)),
                ('client', models.ForeignKey(help_text='Client who sent this request', on_delete=django.db.models.deletion.CASCADE, related_name='sent_case_requests', to='clients.clientprofile')),
                ('lawyer', models.ForeignKey(help_text='Lawyer who is requested', on_delete=django.db.models.deletion.CASCADE, related_name='case_requests', to='lawyers.lawyerprofile')),
            ],
            options={
                'verbose_name': 'Case Request',
                'verbose_name_plural': 'Case Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
