# Generated by Django 6.0.3 on 2026-06-25 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0009_caserequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caserequest',
            name='documents_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When documents were submitted', null=True),
        ),
        migrations.AddField(
            model_name='caserequest',
            name='documents_verified_at',
            field=models.DateTimeField(blank=True, help_text='When documents were verified by admin', null=True),
        ),
        migrations.AlterField(
            model_name='caserequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DOCUMENTS_PENDING', 'Waiting for Documents'), ('DOCUMENTS_SUBMITTED', 'Documents Submitted'), ('DOCUMENTS_VERIFIED', 'Documents Verified'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('marriage_cert', 'Marriage Certificate'), ('address_proof', 'Address Proof'), ('income_proof', 'Income Proof'), ('passport', 'Passport'), ('affidavit', 'Affidavits')], help_text='Type of document', max_length=20)),
                ('document_file', models.FileField(help_text='Uploaded document file', upload_to='case_documents/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When document was uploaded')),
                ('case_request', models.ForeignKey(help_text='Associated case request', on_delete=django.db.models.deletion.CASCADE, related_name='case_documents', to='lawyers.caserequest')),
            ],
            options={
                'verbose_name': 'Case Document',
                'verbose_name_plural': 'Case Documents',
                'ordering': ['-uploaded_at'],
                'unique_together': {('case_request', 'document_type')},
            },
        ),
        migrations.CreateModel(
            name='CaseDocumentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Verification status', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When document was verified', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection if applicable', null=True)),
                ('document', models.OneToOneField(help_text='Associated document', on_delete=django.db.models.deletion.CASCADE, related_name='casedocumentverification', to='lawyers.casedocument')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Admin who verified this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_case_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case Document Verification',
                'verbose_name_plural': 'Case Document Verifications',
                'ordering': ['-verified_at'],
            },
        ),
    ]
