# Generated by Django 6.0.3 on 2026-06-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0010_caserequest_documents_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caserequest',
            name='workflow_stage',
            field=models.CharField(choices=[('CASE_CREATED', 'Case Created'), ('DOCUMENT_VERIFICATION', 'Document Verification'), ('LAWYER_ASSIGNED', 'Lawyer Assigned'), ('PETITION_DRAFTED', 'Petition Drafted'), ('PETITION_FILED', 'Petition Filed'), ('FIRST_MOTION', 'First Motion'), ('SECOND_MOTION', 'Second Motion'), ('DECREE_ISSUED', 'Decree Issued'), ('COMPLETED', 'Completed')], default='CASE_CREATED', help_text='Latest completed workflow milestone for the case', max_length=30),
        ),
        migrations.AddField(
            model_name='caserequest',
            name='workflow_stage_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the workflow stage was last updated', null=True),
        ),
        migrations.AlterField(
            model_name='caserequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DOCUMENTS_PENDING', 'Waiting for Documents'), ('DOCUMENTS_SUBMITTED', 'Documents Submitted'), ('DOCUMENTS_VERIFIED', 'Documents Verified'), ('ACCEPTED', 'Accepted'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
