# Generated by Django 6.0.3 on 2026-06-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0012_casemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='casemessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='casemessage',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
