# Generated by Django 6.0.3 on 2026-06-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyers', '0013_casemessage_attachment_alter_casemessage_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyerprofile',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of client ratings received'),
        ),
        migrations.AddField(
            model_name='lawyerprofile',
            name='rating_total',
            field=models.PositiveIntegerField(default=0, help_text='Sum of all client rating values'),
        ),
    ]
