# Generated by Django 6.0.3 on 2026-06-26 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_deletedclientprofile'),
        ('lawyers', '0014_lawyerprofile_rating_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawyerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Star rating value from 1 to 5')),
                ('review_text', models.TextField(blank=True, help_text='Optional review details from the client')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the rating was submitted')),
                ('client', models.ForeignKey(help_text='Client who submitted the rating', on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_ratings', to='clients.clientprofile')),
                ('lawyer', models.ForeignKey(help_text='Lawyer being rated', on_delete=django.db.models.deletion.CASCADE, related_name='client_ratings', to='lawyers.lawyerprofile')),
            ],
            options={
                'verbose_name': 'Lawyer Rating',
                'verbose_name_plural': 'Lawyer Ratings',
                'ordering': ['-created_at'],
                'unique_together': {('lawyer', 'client')},
            },
        ),
    ]
