# Generated by Django 6.0.3 on 2026-06-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text="Client's profile picture", null=True, upload_to='client_pictures/'),
        ),
    ]
