# Generated by Django 6.0.3 on 2026-06-23 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='alternate_mobile_number',
            field=models.CharField(blank=True, help_text="Client's alternate mobile number (optional)", max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be in Indian format (10 digits starting with 6-9, or +91...', regex='^(\\+91|0)?[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='mobile_number',
            field=models.CharField(blank=True, help_text="Client's primary mobile number (10 digits)", max_length=13, validators=[django.core.validators.RegexValidator(message='Phone number must be in Indian format (10 digits starting with 6-9, or +91...', regex='^(\\+91|0)?[6-9]\\d{9}$')]),
        ),
    ]
