# Generated by Django 6.0.3 on 2026-06-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clientprofile_alternate_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the client profile was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag for a client profile'),
        ),
    ]
