# Generated by Django 6.0.3 on 2026-06-24 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clientprofile_deleted_at_clientprofile_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedClientProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Deleted Client Profile',
                'verbose_name_plural': 'Deleted Client Profiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clients.clientprofile',),
        ),
    ]
