# Generated by Django 6.0.3 on 2026-06-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_deletedclientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='address',
            field=models.CharField(blank=True, help_text="Client's residential address", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='pincode',
            field=models.CharField(blank=True, help_text="Client's postal code (6 digits)", max_length=6, null=True),
        ),
    ]
